export interface Question {
  id: string
  tier: number
  question: string
  answers: string[]
  correctIndex: number
}

const QUESTIONS_BY_TIER: Record<number, Question[]> = {
  1: [
    {id:'1a',tier:1,question:'What is the boiling point of water in Celsius?',answers:['80°C','90°C','100°C','120°C'],correctIndex:2},
    {id:'1b',tier:1,question:'How many days are in a leap year?',answers:['364','365','366','367'],correctIndex:2},
    {id:'1c',tier:1,question:'Which ocean is the smallest?',answers:['Atlantic','Indian','Arctic','Pacific'],correctIndex:2},
    {id:'1d',tier:1,question:'What is the capital of Australia?',answers:['Sydney','Melbourne','Canberra','Perth'],correctIndex:2},
    {id:'1e',tier:1,question:'How many bones are in the adult human body?',answers:['186','206','226','256'],correctIndex:1},
    {id:'1f',tier:1,question:'What year did World War I begin?',answers:['1912','1913','1914','1915'],correctIndex:2},
    {id:'1g',tier:1,question:'Which gas makes up most of the Earth atmosphere?',answers:['Oxygen','Carbon Dioxide','Nitrogen','Argon'],correctIndex:2},
    {id:'1h',tier:1,question:'What is the longest river in the world?',answers:['Amazon','Nile','Mississippi','Yangtze'],correctIndex:1},
    {id:'1i',tier:1,question:'Which planet is closest to the Sun?',answers:['Venus','Mercury','Mars','Earth'],correctIndex:1},
    {id:'1j',tier:1,question:'What is the largest organ in the human body?',answers:['Liver','Brain','Skin','Heart'],correctIndex:2},
    {id:'1k',tier:1,question:'How many continents are there on Earth?',answers:['5','6','7','8'],correctIndex:2},
    {id:'1l',tier:1,question:'Which animal is known as the King of the Jungle?',answers:['Tiger','Lion','Elephant','Gorilla'],correctIndex:1},
    {id:'1m',tier:1,question:'What is the smallest prime number?',answers:['0','1','2','3'],correctIndex:2},
    {id:'1n',tier:1,question:'Which country has the largest land area?',answers:['China','USA','Canada','Russia'],correctIndex:3},
    {id:'1o',tier:1,question:'What color are emeralds?',answers:['Red','Blue','Green','Purple'],correctIndex:2},
    {id:'1p',tier:1,question:'How many teeth does an adult human typically have?',answers:['28','30','32','36'],correctIndex:2},
    {id:'1q',tier:1,question:'What is the freezing point of water in Fahrenheit?',answers:['0°F','32°F','40°F','100°F'],correctIndex:1},
    {id:'1r',tier:1,question:'Which bird is a symbol of peace?',answers:['Eagle','Hawk','Dove','Raven'],correctIndex:2},
    {id:'1s',tier:1,question:'What is the most spoken language in the world by native speakers?',answers:['English','Spanish','Mandarin','Hindi'],correctIndex:2},
    {id:'1t',tier:1,question:'Which month has 28 or 29 days?',answers:['January','June','February','December'],correctIndex:2},
    {id:'1u',tier:1,question:'What is the chemical symbol for gold?',answers:['Go','Gd','Au','Ag'],correctIndex:2},
    {id:'1v',tier:1,question:'How many sides does a hexagon have?',answers:['5','6','7','8'],correctIndex:1},
    {id:'1w',tier:1,question:'Which famous clock is in London?',answers:['Big Ben','Colosseum','Eiffel Tower','Statue of Liberty'],correctIndex:0},
    {id:'1x',tier:1,question:'What is the largest mammal?',answers:['Elephant','Blue Whale','Giraffe','Hippopotamus'],correctIndex:1},
    {id:'1y',tier:1,question:'Which fruit is known as the king of fruits?',answers:['Apple','Mango','Banana','Pineapple'],correctIndex:1},
    {id:'1z',tier:1,question:'How many legs does a spider have?',answers:['6','8','10','12'],correctIndex:1},
    {id:'1aa',tier:1,question:'What is the capital of Egypt?',answers:['Alexandria','Luxor','Cairo','Giza'],correctIndex:2},
    {id:'1ab',tier:1,question:'Which planet is known as the Morning Star?',answers:['Mars','Jupiter','Venus','Saturn'],correctIndex:2},
    {id:'1ac',tier:1,question:'What is the most abundant gas in the universe?',answers:['Oxygen','Helium','Nitrogen','Hydrogen'],correctIndex:3},
    {id:'1ad',tier:1,question:'How many millimeters in a centimeter?',answers:['5','10','15','100'],correctIndex:1},
    {id:'1ae',tier:1,question:'Which instrument has 88 keys?',answers:['Violin','Guitar','Piano','Flute'],correctIndex:2},
    {id:'1af',tier:1,question:'What is the tallest animal on Earth?',answers:['Elephant','Giraffe','Camel','Horse'],correctIndex:1},
    {id:'1ag',tier:1,question:'Which country invented paper?',answers:['India','Egypt','China','Greece'],correctIndex:2},
    {id:'1ah',tier:1,question:'What color is a ruby?',answers:['Blue','Green','Red','Yellow'],correctIndex:2},
    {id:'1ai',tier:1,question:'How many players are on a soccer team?',answers:['9','10','11','12'],correctIndex:2},
    {id:'1aj',tier:1,question:'Which is the fastest land animal?',answers:['Lion','Cheetah','Horse','Gazelle'],correctIndex:1},
    {id:'1ak',tier:1,question:'What is the currency of Japan?',answers:['Yuan','Won','Yen','Ringgit'],correctIndex:2},
    {id:'1al',tier:1,question:'How many strings does a standard guitar have?',answers:['4','5','6','7'],correctIndex:2},
    {id:'1am',tier:1,question:'Which vitamin is produced by sunlight?',answers:['Vitamin A','Vitamin B','Vitamin C','Vitamin D'],correctIndex:3},
    {id:'1an',tier:1,question:'What is the largest desert in the world?',answers:['Gobi','Sahara','Arabian','Antarctic'],correctIndex:3},
    {id:'1ao',tier:1,question:'Which mountain is the tallest on Earth?',answers:['K2','Everest','Kilimanjaro','Denali'],correctIndex:1},
    {id:'1ap',tier:1,question:'What is the chemical symbol for water?',answers:['Wt','H2O','H2','O2'],correctIndex:1},
    {id:'1aq',tier:1,question:'How many days are in a week?',answers:['5','6','7','8'],correctIndex:2},
    {id:'1ar',tier:1,question:'Which country is the largest by population?',answers:['China','India','USA','Indonesia'],correctIndex:1},
    {id:'1as',tier:1,question:'What do bees produce?',answers:['Wax','Honey','Milk','Silk'],correctIndex:1},
    {id:'1at',tier:1,question:'Which American city is known as the Big Apple?',answers:['Los Angeles','Chicago','New York','Miami'],correctIndex:2},
    {id:'1au',tier:1,question:'What part of the plant conducts photosynthesis?',answers:['Root','Stem','Leaf','Flower'],correctIndex:2},
    {id:'1av',tier:1,question:'How many years in a century?',answers:['50','100','200','1000'],correctIndex:1},
    {id:'1aw',tier:1,question:'Which animal is the largest species of shark?',answers:['Great White','Tiger Shark','Whale Shark','Hammerhead'],correctIndex:2},
    {id:'1ax',tier:1,question:'What gas do plants release during photosynthesis?',answers:['Carbon Dioxide','Nitrogen','Oxygen','Hydrogen'],correctIndex:2},
    {id:'1ay',tier:1,question:'Which country invented pizza?',answers:['France','Spain','Italy','Greece'],correctIndex:2},
    {id:'1az',tier:1,question:'What is the hardest natural substance?',answers:['Iron','Diamond','Steel','Quartz'],correctIndex:1},
    {id:'1ba',tier:1,question:'How many degrees in a right angle?',answers:['45','60','90','180'],correctIndex:2},
    {id:'1bb',tier:1,question:'What is the largest organ inside the human body?',answers:['Heart','Lungs','Liver','Brain'],correctIndex:2},
    {id:'1bc',tier:1,question:'Which planet has the most moons?',answers:['Mars','Jupiter','Saturn','Neptune'],correctIndex:2},
    {id:'1bd',tier:1,question:'What is the official language of Brazil?',answers:['Spanish','Portuguese','French','English'],correctIndex:1},
    {id:'1be',tier:1,question:'How many sides does a stop sign have?',answers:['6','7','8','10'],correctIndex:2},
    {id:'1bf',tier:1,question:'Which animal is known to change color for camouflage?',answers:['Lizard','Chameleon','Octopus','Frog'],correctIndex:1},
    {id:'1bg',tier:1,question:'What is the smallest bird in the world?',answers:['Sparrow','Hummingbird','Finch','Wren'],correctIndex:1},
    {id:'1bh',tier:1,question:'Which is the most widely consumed beverage after water?',answers:['Coffee','Tea','Milk','Juice'],correctIndex:1},
    {id:'1bi',tier:1,question:'How many zeros are in one million?',answers:['4','5','6','7'],correctIndex:2},
    {id:'1bj',tier:1,question:'What is the capital of Canada?',answers:['Toronto','Vancouver','Montreal','Ottawa'],correctIndex:3},
    {id:'1bk',tier:1,question:'Which metal is liquid at room temperature?',answers:['Iron','Mercury','Gold','Silver'],correctIndex:1},
    {id:'1bl',tier:1,question:'How many minutes are in an hour?',answers:['30','45','60','100'],correctIndex:2},
    {id:'1bm',tier:1,question:'Which fruit has its seeds on the outside?',answers:['Apple','Orange','Strawberry','Banana'],correctIndex:2},
    {id:'1bn',tier:1,question:'What is the primary ingredient in bread?',answers:['Rice','Flour','Corn','Oats'],correctIndex:1},
    {id:'1bo',tier:1,question:'Which animal is the fastest in water?',answers:['Dolphin','Sailfish','Shark','Whale'],correctIndex:1},
    {id:'1bp',tier:1,question:'What is the number of Harry Potter books?',answers:['5','6','7','8'],correctIndex:2},
    {id:'1bq',tier:1,question:'Which country is the largest island in the world?',answers:['Madagascar','Indonesia','Greenland','Japan'],correctIndex:2},
    {id:'1br',tier:1,question:'How many hours are in a day?',answers:['12','24','36','48'],correctIndex:1},
    {id:'1bs',tier:1,question:'Which blood type is the universal donor?',answers:['A','B','AB','O'],correctIndex:3},
    {id:'1bt',tier:1,question:'What is the chemical symbol for silver?',answers:['Si','Sv','Ag','Au'],correctIndex:2},
    {id:'1bu',tier:1,question:'Which continent has the most countries?',answers:['Asia','Europe','Africa','South America'],correctIndex:2},
    {id:'1bv',tier:1,question:'What instrument measures temperature?',answers:['Barometer','Thermometer','Speedometer','Hygrometer'],correctIndex:1},
    {id:'1bw',tier:1,question:'How many colors are in a rainbow?',answers:['5','6','7','8'],correctIndex:2},
    {id:'1bx',tier:1,question:'Which planet has a Great Red Spot?',answers:['Mars','Venus','Jupiter','Saturn'],correctIndex:2},
    {id:'1by',tier:1,question:'What is the most consumed manufactured drink in the world?',answers:['Coffee','Soda','Tea','Beer'],correctIndex:0},
    {id:'1bz',tier:1,question:'Which animal can sleep for up to three years?',answers:['Bear','Frog','Snail','Turtle'],correctIndex:2},
    {id:'1ca',tier:1,question:'How many hearts does an octopus have?',answers:['1','2','3','4'],correctIndex:2},
    {id:'1cb',tier:1,question:'Which country is the smallest by area?',answers:['Monaco','Vatican City','Malta','San Marino'],correctIndex:1},
    {id:'1cc',tier:1,question:'What is the most popular sport in the world?',answers:['Cricket','Basketball','Soccer','Tennis'],correctIndex:2},
    {id:'1cd',tier:1,question:'Which gas is responsible for the greenhouse effect?',answers:['Oxygen','Nitrogen','Carbon Dioxide','Helium'],correctIndex:2},
    {id:'1ce',tier:1,question:'What is the capital of Italy?',answers:['Milan','Venice','Rome','Naples'],correctIndex:2},
    {id:'1cf',tier:1,question:'How many planets are in our solar system?',answers:['7','8','9','10'],correctIndex:1},
    {id:'1cg',tier:1,question:'Which food is the main source of energy for the body?',answers:['Protein','Fat','Carbohydrates','Vitamins'],correctIndex:2},
    {id:'1ch',tier:1,question:'What is the largest species of big cat?',answers:['Lion','Tiger','Leopard','Jaguar'],correctIndex:1},
    {id:'1ci',tier:1,question:'Which country is known as the Land of the Rising Sun?',answers:['China','Korea','Japan','Thailand'],correctIndex:2},
    {id:'1cj',tier:1,question:'What is the primary function of red blood cells?',answers:['Fight infection','Carry oxygen','Clot blood','Produce antibodies'],correctIndex:1},
    {id:'1ck',tier:1,question:'How many fingers does a typical human have on one hand?',answers:['4','5','6','7'],correctIndex:1},
    {id:'1cl',tier:1,question:'Which element is needed for combustion?',answers:['Nitrogen','Hydrogen','Oxygen','Carbon'],correctIndex:2},
    {id:'1cm',tier:1,question:'What is the currency of the United Kingdom?',answers:['Euro','Dollar','Pound','Franc'],correctIndex:2},
    {id:'1cn',tier:1,question:'Which animal lays the largest eggs?',answers:['Eagle','Ostrich','Emu','Swan'],correctIndex:1},
    {id:'1co',tier:1,question:'How many legs does a butterfly have?',answers:['4','5','6','8'],correctIndex:2},
    {id:'1cp',tier:1,question:'What is the chemical symbol for sodium?',answers:['So','Sd','Na','S'],correctIndex:2},
    {id:'1cq',tier:1,question:'Which country is famous for the tulip?',answers:['France','Netherlands','Denmark','Sweden'],correctIndex:1},
    {id:'1cr',tier:1,question:'What is the largest type of bear?',answers:['Brown Bear','Polar Bear','Black Bear','Grizzly'],correctIndex:1},
    {id:'1cs',tier:1,question:'Which season comes after winter?',answers:['Summer','Fall','Spring','Monsoon'],correctIndex:2},
    {id:'1ct',tier:1,question:'How many sides does a triangle have?',answers:['2','3','4','5'],correctIndex:1},
    {id:'1cu',tier:1,question:'What is the capital of France?',answers:['London','Berlin','Paris','Madrid'],correctIndex:2},
    {id:'1cv',tier:1,question:'Which is the longest bone in the human body?',answers:['Spine','Femur','Humerus','Tibia'],correctIndex:1},
    {id:'1cw',tier:1,question:'What type of animal is a dolphin?',answers:['Fish','Reptile','Mammal','Amphibian'],correctIndex:2},
    {id:'1cx',tier:1,question:'Which country invented the compass?',answers:['India','China','Greece','Arabia'],correctIndex:1},
    {id:'1cy',tier:1,question:'How many letters are in the English alphabet?',answers:['24','25','26','27'],correctIndex:2},
    {id:'1cz',tier:1,question:'What is the primary color of a polar bear skin?',answers:['White','Black','Pink','Gray'],correctIndex:1},
    {id:'1da',tier:1,question:'Which instrument is used to measure atmospheric pressure?',answers:['Thermometer','Barometer','Hygrometer','Anemometer'],correctIndex:1},
    {id:'1db',tier:1,question:'What is the most abundant element in the Earth crust?',answers:['Iron','Aluminum','Oxygen','Silicon'],correctIndex:2},
    {id:'1dc',tier:1,question:'Which country is the largest producer of coffee?',answers:['Colombia','Vietnam','Brazil','Ethiopia'],correctIndex:2},
    {id:'1dd',tier:1,question:'How many days does it take for Earth to orbit the Sun?',answers:['360','365','370','380'],correctIndex:1},
    {id:'1de',tier:1,question:'What is the smallest planet in our solar system?',answers:['Mars','Mercury','Venus','Pluto'],correctIndex:1},
  ],
  2: [
    {id:'2a',tier:2,question:'Who wrote Romeo and Juliet?',answers:['Charles Dickens','William Shakespeare','Jane Austen','Mark Twain'],correctIndex:1},
    {id:'2b',tier:2,question:'What is the powerhouse of the cell?',answers:['Nucleus','Ribosome','Mitochondria','Golgi'],correctIndex:2},
    {id:'2c',tier:2,question:'In which year did the Titanic sink?',answers:['1910','1911','1912','1913'],correctIndex:2},
    {id:'2d',tier:2,question:'What is the main ingredient in guacamole?',answers:['Tomato','Avocado','Onion','Pepper'],correctIndex:1},
    {id:'2e',tier:2,question:'Which element has the atomic number 1?',answers:['Helium','Lithium','Hydrogen','Carbon'],correctIndex:2},
    {id:'2f',tier:2,question:'What is the capital of Spain?',answers:['Barcelona','Valencia','Madrid','Seville'],correctIndex:2},
    {id:'2g',tier:2,question:'How many teeth does an adult human have including wisdom teeth?',answers:['28','30','32','34'],correctIndex:2},
    {id:'2h',tier:2,question:'Which gas do humans exhale?',answers:['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'],correctIndex:2},
    {id:'2i',tier:2,question:'What is the Great Wall of China made primarily of?',answers:['Brick and Wood','Stone and Earth','Concrete and Steel','Marble and Granite'],correctIndex:1},
    {id:'2j',tier:2,question:'Which animal is the symbol of the World Wildlife Fund?',answers:['Tiger','Panda','Elephant','Rhino'],correctIndex:1},
    {id:'2k',tier:2,question:'What is the pH of pure water?',answers:['5','6','7','8'],correctIndex:2},
    {id:'2l',tier:2,question:'Which country gifted the Statue of Liberty to the USA?',answers:['Britain','Spain','France','Germany'],correctIndex:2},
    {id:'2m',tier:2,question:'How many bones are in the human hand?',answers:['19','23','27','31'],correctIndex:2},
    {id:'2n',tier:2,question:'What was the first manned Moon landing mission?',answers:['Apollo 12','Apollo 11','Apollo 13','Apollo 8'],correctIndex:1},
    {id:'2o',tier:2,question:'Which blood type is the rarest?',answers:['A','B','AB','O'],correctIndex:2},
    {id:'2p',tier:2,question:'What is the national sport of Canada?',answers:['Ice Hockey','Lacrosse','Curling','Skiing'],correctIndex:1},
    {id:'2q',tier:2,question:'Which element is a liquid metal?',answers:['Gold','Silver','Mercury','Lead'],correctIndex:2},
    {id:'2r',tier:2,question:'How many chromosomes do humans have?',answers:['23','44','46','48'],correctIndex:2},
    {id:'2s',tier:2,question:'What is the largest lake in Africa?',answers:['Lake Victoria','Lake Tanganyika','Lake Malawi','Lake Chad'],correctIndex:0},
    {id:'2t',tier:2,question:'Which year did the Berlin Wall fall?',answers:['1987','1988','1989','1990'],correctIndex:2},
    {id:'2u',tier:2,question:'What is the chemical formula of table salt?',answers:['NaCl','KCl','CaCO3','NaHCO3'],correctIndex:0},
    {id:'2v',tier:2,question:'Who painted the Mona Lisa?',answers:['Michelangelo','Raphael','Leonardo da Vinci','Donatello'],correctIndex:2},
    {id:'2w',tier:2,question:'How many states are in the United States?',answers:['48','49','50','52'],correctIndex:2},
    {id:'2x',tier:2,question:'Which planet has the most volcanoes?',answers:['Earth','Mars','Venus','Jupiter'],correctIndex:2},
    {id:'2y',tier:2,question:'What is the speed of sound approximately?',answers:['343 m/s','500 m/s','700 m/s','1000 m/s'],correctIndex:0},
    {id:'2z',tier:2,question:'Which musical instrument has the most strings?',answers:['Guitar','Violin','Harp','Cello'],correctIndex:2},
    {id:'2aa',tier:2,question:'What is the currency of India?',answers:['Rupee','Rupiah','Taka','Ringgit'],correctIndex:0},
    {id:'2ab',tier:2,question:'How many time zones does Russia have?',answers:['7','9','11','13'],correctIndex:2},
    {id:'2ac',tier:2,question:'Which animal is known as the ship of the desert?',answers:['Horse','Donkey','Camel','Llama'],correctIndex:2},
    {id:'2ad',tier:2,question:'What is the main component of air?',answers:['Oxygen','Carbon Dioxide','Nitrogen','Argon'],correctIndex:2},
    {id:'2ae',tier:2,question:'What is the tallest building in the world?',answers:['Shanghai Tower','Burj Khalifa','Abraj Al-Bait','One World Trade'],correctIndex:1},
    {id:'2af',tier:2,question:'Which country is the largest oil producer?',answers:['Saudi Arabia','USA','Russia','Iraq'],correctIndex:1},
    {id:'2ag',tier:2,question:'What is the average human body temperature in Celsius?',answers:['36°C','37°C','38°C','39°C'],correctIndex:1},
    {id:'2ah',tier:2,question:'Which vitamin is found in citrus fruits?',answers:['Vitamin A','Vitamin B','Vitamin C','Vitamin D'],correctIndex:2},
    {id:'2ai',tier:2,question:'What is the deepest ocean trench?',answers:['Tonga Trench','Mariana Trench','Puerto Rico Trench','Java Trench'],correctIndex:1},
    {id:'2aj',tier:2,question:'How many players are in a baseball team?',answers:['7','8','9','10'],correctIndex:2},
    {id:'2ak',tier:2,question:'Which country is the largest by area in Africa?',answers:['Sudan','DRC','Algeria','Nigeria'],correctIndex:2},
    {id:'2al',tier:2,question:'What is the second most abundant element in the universe?',answers:['Hydrogen','Helium','Oxygen','Carbon'],correctIndex:1},
    {id:'2am',tier:2,question:'Which animal can regenerate its limbs?',answers:['Lizard','Starfish','Salamander','Crab'],correctIndex:2},
    {id:'2an',tier:2,question:'What is the capital of South Korea?',answers:['Seoul','Busan','Incheon','Pyongyang'],correctIndex:0},
    {id:'2ao',tier:2,question:'How many elements are in the periodic table?',answers:['102','110','118','126'],correctIndex:2},
    {id:'2ap',tier:2,question:'Which bird cannot fly?',answers:['Eagle','Penguin','Hawk','Falcon'],correctIndex:1},
    {id:'2aq',tier:2,question:'What is the largest continent?',answers:['Africa','North America','Asia','Europe'],correctIndex:2},
    {id:'2ar',tier:2,question:'Which country had the first written constitution?',answers:['France','USA','UK','Poland'],correctIndex:1},
    {id:'2as',tier:2,question:'What is the study of fossils called?',answers:['Archaeology','Paleontology','Geology','Anthropology'],correctIndex:1},
    {id:'2at',tier:2,question:'How many rings are on the Olympic flag?',answers:['4','5','6','7'],correctIndex:1},
    {id:'2au',tier:2,question:'Which metal is the best conductor of electricity?',answers:['Copper','Gold','Silver','Aluminum'],correctIndex:2},
    {id:'2av',tier:2,question:'What is the capital of Argentina?',answers:['Buenos Aires','Santiago','Lima','Brasilia'],correctIndex:0},
    {id:'2aw',tier:2,question:'Which disease is caused by a lack of vitamin C?',answers:['Rickets','Scurvy','Anemia','Beriberi'],correctIndex:1},
    {id:'2ax',tier:2,question:'How many colors are in the visible spectrum?',answers:['5','6','7','8'],correctIndex:2},
    {id:'2ay',tier:2,question:'What is the name of the largest moon of Saturn?',answers:['Europa','Ganymede','Titan','Io'],correctIndex:2},
    {id:'2az',tier:2,question:'Which year did World War II end?',answers:['1943','1944','1945','1946'],correctIndex:2},
    {id:'2ba',tier:2,question:'What is the main ingredient in tofu?',answers:['Rice','Soybeans','Wheat','Corn'],correctIndex:1},
    {id:'2bb',tier:2,question:'Which planet is the hottest?',answers:['Mercury','Venus','Mars','Jupiter'],correctIndex:1},
    {id:'2bc',tier:2,question:'What is the largest island in the Mediterranean?',answers:['Crete','Cyprus','Sicily','Sardinia'],correctIndex:2},
    {id:'2bd',tier:2,question:'Which country is both in Europe and Asia?',answers:['Greece','Turkey','Egypt','Iran'],correctIndex:1},
    {id:'2be',tier:2,question:'What is the SI unit of force?',answers:['Joule','Newton','Watt','Pascal'],correctIndex:1},
    {id:'2bf',tier:2,question:'How many bones does a shark have?',answers:['100','200','0','500'],correctIndex:2},
    {id:'2bg',tier:2,question:'Which composer became deaf later in life?',answers:['Mozart','Bach','Beethoven','Chopin'],correctIndex:2},
    {id:'2bh',tier:2,question:'What is the most widely spoken language in South America?',answers:['Spanish','Portuguese','French','English'],correctIndex:0},
    {id:'2bi',tier:2,question:'Which gas is used in balloons to make them float?',answers:['Hydrogen','Helium','Nitrogen','Argon'],correctIndex:1},
    {id:'2bj',tier:2,question:'What is the longest river in Asia?',answers:['Mekong','Ganges','Yangtze','Yellow River'],correctIndex:2},
    {id:'2bk',tier:2,question:'Which civilization built Machu Picchu?',answers:['Aztec','Maya','Inca','Olmec'],correctIndex:2},
    {id:'2bl',tier:2,question:'How many Earths can fit inside the Sun?',answers:['100,000','500,000','1 million','10 million'],correctIndex:2},
    {id:'2bm',tier:2,question:'What is the smallest country in the world by population?',answers:['Monaco','Vatican City','Nauru','Tuvalu'],correctIndex:1},
    {id:'2bn',tier:2,question:'Which fruit has the highest vitamin C content?',answers:['Orange','Lemon','Kiwi','Kakadu plum'],correctIndex:3},
    {id:'2bo',tier:2,question:'What is the capital of Turkey?',answers:['Istanbul','Ankara','Izmir','Antalya'],correctIndex:1},
    {id:'2bp',tier:2,question:'Which year was the United Nations founded?',answers:['1942','1945','1948','1950'],correctIndex:1},
    {id:'2bq',tier:2,question:'What is the largest waterfall in the world by volume?',answers:['Niagara','Victoria','Iguazu','Angel'],correctIndex:1},
    {id:'2br',tier:2,question:'Which metal is used in thermometers?',answers:['Gold','Silver','Mercury','Copper'],correctIndex:2},
    {id:'2bs',tier:2,question:'How many chambers does the human heart have?',answers:['2','3','4','5'],correctIndex:2},
    {id:'2bt',tier:2,question:'What is the primary gas in the atmospheres of Mars and Venus?',answers:['Oxygen','Nitrogen','Carbon Dioxide','Argon'],correctIndex:2},
    {id:'2bu',tier:2,question:'Which ocean lies between Africa and Australia?',answers:['Atlantic','Pacific','Indian','Southern'],correctIndex:2},
    {id:'2bv',tier:2,question:'What is the largest organ in the human body by weight?',answers:['Brain','Liver','Skin','Lungs'],correctIndex:2},
    {id:'2bw',tier:2,question:'Which country is home to the kangaroo?',answers:['New Zealand','South Africa','Australia','Brazil'],correctIndex:2},
    {id:'2bx',tier:2,question:'What is the chemical element with symbol K?',answers:['Krypton','Potassium','Kalium','Krypton'],correctIndex:1},
    {id:'2by',tier:2,question:'How long does it take for blood to circulate through the body?',answers:['10 seconds','30 seconds','1 minute','2 minutes'],correctIndex:2},
    {id:'2bz',tier:2,question:'Which country has the longest coastline?',answers:['Australia','USA','Canada','Russia'],correctIndex:2},
    {id:'2ca',tier:2,question:'What is the most abundant mineral in the human body?',answers:['Iron','Calcium','Potassium','Sodium'],correctIndex:1},
    {id:'2cb',tier:2,question:'Which continent is the least populated?',answers:['Europe','Australia','Antarctica','South America'],correctIndex:2},
    {id:'2cc',tier:2,question:'What is the only mammal capable of true flight?',answers:['Flying squirrel','Bat','Flying fox','Pterosaur'],correctIndex:1},
    {id:'2cd',tier:2,question:'Which year was the first iPhone released?',answers:['2005','2006','2007','2008'],correctIndex:2},
    {id:'2ce',tier:2,question:'What is the largest species of penguin?',answers:['King Penguin','Emperor Penguin','Adelie Penguin','Gentoo Penguin'],correctIndex:1},
    {id:'2cf',tier:2,question:'Which country has the most pyramids?',answers:['Egypt','Mexico','Sudan','Iraq'],correctIndex:2},
    {id:'2cg',tier:2,question:'What is the SI unit of electric current?',answers:['Volt','Watt','Ampere','Ohm'],correctIndex:2},
    {id:'2ch',tier:2,question:'How many natural satellites does Earth have?',answers:['0','1','2','3'],correctIndex:1},
    {id:'2ci',tier:2,question:'Which vitamin helps with blood clotting?',answers:['Vitamin A','Vitamin C','Vitamin K','Vitamin E'],correctIndex:2},
    {id:'2cj',tier:2,question:'What is the longest mountain range in the world?',answers:['Himalayas','Andes','Rockies','Alps'],correctIndex:1},
    {id:'2ck',tier:2,question:'Which country drinks the most coffee per capita?',answers:['Italy','USA','Finland','Brazil'],correctIndex:2},
    {id:'2cl',tier:2,question:'What type of rock is formed from cooled lava?',answers:['Sedimentary','Metamorphic','Igneous','Fossilized'],correctIndex:2},
    {id:'2cm',tier:2,question:'Which animal has the longest gestation period?',answers:['Elephant','Giraffe','Whale','Rhinoceros'],correctIndex:0},
    {id:'2cn',tier:2,question:'What is the second-largest planet in the solar system?',answers:['Jupiter','Neptune','Uranus','Saturn'],correctIndex:3},
    {id:'2co',tier:2,question:'Which country invented zero as a number?',answers:['Greece','China','India','Arabia'],correctIndex:2},
    {id:'2cp',tier:2,question:'What is the largest freshwater lake by surface area?',answers:['Lake Superior','Lake Victoria','Caspian Sea','Lake Baikal'],correctIndex:0},
    {id:'2cq',tier:2,question:'How many years does it take for Pluto to orbit the Sun?',answers:['88 years','165 years','248 years','365 years'],correctIndex:2},
    {id:'2cr',tier:2,question:'Which element is a noble gas?',answers:['Chlorine','Fluorine','Neon','Iodine'],correctIndex:2},
    {id:'2cs',tier:2,question:'What is the most populous city in the world?',answers:['Tokyo','Delhi','Shanghai','Mumbai'],correctIndex:1},
    {id:'2ct',tier:2,question:'Which disease is caused by the Plasmodium parasite?',answers:['Dengue','Malaria','Typhoid','Cholera'],correctIndex:1},
    {id:'2cu',tier:2,question:'What is the largest animal that ever lived?',answers:['Elephant','Blue Whale','Brontosaurus','Megalodon'],correctIndex:1},
    {id:'2cv',tier:2,question:'Which country is the world largest tea producer?',answers:['India','Kenya','Sri Lanka','China'],correctIndex:3},
    {id:'2cw',tier:2,question:'How many bones are in the human skull?',answers:['8','14','22','28'],correctIndex:2},
    {id:'2cx',tier:2,question:'What is the largest coral reef system?',answers:['Great Barrier Reef','Mesoamerican Barrier Reef','New Caledonia Barrier Reef','Red Sea Coral'],correctIndex:0},
    {id:'2cy',tier:2,question:'Which artist is known for painting Campbell soup cans?',answers:['Picasso','Warhol','Lichtenstein','Dali'],correctIndex:1},
    {id:'2cz',tier:2,question:'What is the only letter not appearing in any US state name?',answers:['X','Z','Q','J'],correctIndex:2},
    {id:'2da',tier:2,question:'Which element is used in semiconductor chips?',answers:['Carbon','Silicon','Germanium','Tin'],correctIndex:1},
    {id:'2db',tier:2,question:'What is the largest national park in the world?',answers:['Yellowstone','Serengeti','Northeast Greenland','Wood Buffalo'],correctIndex:2},
    {id:'2dc',tier:2,question:'Which animal has the strongest bite force?',answers:['Lion','Great White Shark','Crocodile','Hippopotamus'],correctIndex:2},
    {id:'2dd',tier:2,question:'How many total keys on a standard piano?',answers:['66','76','88','92'],correctIndex:2},
    {id:'2de',tier:2,question:'What is the capital of Norway?',answers:['Stockholm','Helsinki','Oslo','Copenhagen'],correctIndex:2},
  ],
  3: [
    {id:'3a',tier:3,question:'What is the only metal that is liquid at standard conditions?',answers:['Gallium','Mercury','Cesium','Francium'],correctIndex:1},
    {id:'3b',tier:3,question:'Which element has the chemical symbol Pb?',answers:['Platinum','Plutonium','Lead','Phosphorus'],correctIndex:2},
    {id:'3c',tier:3,question:'What year was the first successful heart transplant?',answers:['1965','1967','1969','1971'],correctIndex:1},
    {id:'3d',tier:3,question:'Who developed the polio vaccine?',answers:['Louis Pasteur','Jonas Salk','Alexander Fleming','Edward Jenner'],correctIndex:1},
    {id:'3e',tier:3,question:'Which country has the most time zones?',answers:['USA','Russia','France','China'],correctIndex:2},
    {id:'3f',tier:3,question:'What is the fourth most abundant element in the universe?',answers:['Helium','Oxygen','Neon','Carbon'],correctIndex:3},
    {id:'3g',tier:3,question:'Which US state was the first to legalize same-sex marriage?',answers:['California','New York','Massachusetts','Vermont'],correctIndex:2},
    {id:'3h',tier:3,question:'What is the oldest university in the world?',answers:['Oxford','Bologna','Al-Azhar','Cambridge'],correctIndex:1},
    {id:'3i',tier:3,question:'Which planet was discovered in 1846?',answers:['Uranus','Neptune','Pluto','Saturn'],correctIndex:1},
    {id:'3j',tier:3,question:'What is the largest muscle in the human body?',answers:['Quadriceps','Gluteus Maximus','Biceps','Latissimus Dorsi'],correctIndex:1},
    {id:'3k',tier:3,question:'Which animal can hold its breath the longest?',answers:['Whale','Dolphin','Turtle','Leatherback Sea Turtle'],correctIndex:3},
    {id:'3l',tier:3,question:'What is the only letter not used in the periodic table symbols?',answers:['J','Q','X','Z'],correctIndex:0},
    {id:'3m',tier:3,question:'Which chemical is responsible for the heat in chili peppers?',answers:['Capsaicin','Piperine','Curcumin','Menthol'],correctIndex:0},
    {id:'3n',tier:3,question:'Who served as the first female Prime Minister of the UK?',answers:['Queen Elizabeth','Margaret Thatcher','Theresa May','Angela Merkel'],correctIndex:1},
    {id:'3o',tier:3,question:'What is the estimated age of the universe?',answers:['4.5 billion','9 billion','13.8 billion','20 billion'],correctIndex:2},
    {id:'3p',tier:3,question:'Which country owns Greenland?',answers:['Iceland','Canada','Denmark','Norway'],correctIndex:2},
    {id:'3q',tier:3,question:'What is the hardest known mineral?',answers:['Corundum','Diamond','Topaz','Quartz'],correctIndex:1},
    {id:'3r',tier:3,question:'Which ocean is the saltiest?',answers:['Pacific','Atlantic','Indian','Arctic'],correctIndex:1},
    {id:'3s',tier:3,question:'What is the largest lake in South America?',answers:['Lake Titicaca','Lake Maracaibo','Lake Poopo','Lake Buenos Aires'],correctIndex:1},
    {id:'3t',tier:3,question:'Which element makes up 50% of the Earth crust by weight?',answers:['Silicon','Aluminum','Oxygen','Iron'],correctIndex:2},
    {id:'3u',tier:3,question:'Who invented the World Wide Web?',answers:['Vint Cerf','Tim Berners-Lee','Bill Gates','Steve Jobs'],correctIndex:1},
    {id:'3v',tier:3,question:'What is the longest-running Broadway show?',answers:['Cats','Les Miserables','The Phantom of the Opera','Chicago'],correctIndex:2},
    {id:'3w',tier:3,question:'Which country has the highest literacy rate?',answers:['Japan','Finland','North Korea','Andorra'],correctIndex:2},
    {id:'3x',tier:3,question:'What is the smallest bone in the human body?',answers:['Stapes','Patella','Phalanx','Coccyx'],correctIndex:0},
    {id:'3y',tier:3,question:'Which city hosted the first modern Olympics in 1896?',answers:['Athens','Paris','London','Rome'],correctIndex:0},
    {id:'3z',tier:3,question:'What is the only mammal that can truly fly?',answers:['Bat','Flying Squirrel','Sugar Glider','Colugo'],correctIndex:0},
    {id:'3aa',tier:3,question:'Which country has the most UNESCO World Heritage Sites?',answers:['Italy','China','Spain','France'],correctIndex:0},
    {id:'3ab',tier:3,question:'What is the highest-grossing film of all time?',answers:['Avengers Endgame','Avatar','Titanic','Star Wars Force Awakens'],correctIndex:1},
    {id:'3ac',tier:3,question:'Which chemical element is named after a continent?',answers:['Americium','Europium','Californium','Francium'],correctIndex:1},
    {id:'3ad',tier:3,question:'What is the most remote inhabited island?',answers:['Easter Island','Tristan da Cunha','St Helena','Fiji'],correctIndex:1},
    {id:'3ae',tier:3,question:'Which river flows through the Grand Canyon?',answers:['Missouri','Rio Grande','Colorado','Snake'],correctIndex:2},
    {id:'3af',tier:3,question:'What is the SI unit of frequency?',answers:['Hertz','Watt','Joule','Decibel'],correctIndex:0},
    {id:'3ag',tier:3,question:'Which country is the largest producer of gold?',answers:['South Africa','China','USA','Australia'],correctIndex:1},
    {id:'3ah',tier:3,question:'What is the deepest lake in the world?',answers:['Lake Tanganyika','Lake Baikal','Caspian Sea','Lake Malawi'],correctIndex:1},
    {id:'3ai',tier:3,question:'How many keys are on a standard computer keyboard?',answers:['101','104','108','112'],correctIndex:1},
    {id:'3aj',tier:3,question:'Which artist painted The Persistence of Memory?',answers:['Picasso','Dali','Magritte','Miro'],correctIndex:1},
    {id:'3ak',tier:3,question:'What is the largest active volcano on Earth?',answers:['Mount Vesuvius','Mauna Loa','Mount Fuji','Krakatoa'],correctIndex:1},
    {id:'3al',tier:3,question:'Which country has the longest railway network?',answers:['Russia','USA','China','India'],correctIndex:2},
    {id:'3am',tier:3,question:'What is the fifth most abundant element in the Earth crust?',answers:['Calcium','Sodium','Potassium','Magnesium'],correctIndex:0},
    {id:'3an',tier:3,question:'Which animal is the only marsupial found in North America?',answers:['Opossum','Kangaroo','Wallaby','Koala'],correctIndex:0},
    {id:'3ao',tier:3,question:'What is the smallest independent state in the world?',answers:['Monaco','San Marino','Vatican City','Liechtenstein'],correctIndex:2},
    {id:'3ap',tier:3,question:'Which civilization built the city of Petra?',answers:['Romans','Greeks','Nabateans','Egyptians'],correctIndex:2},
    {id:'3aq',tier:3,question:'What is the highest-grossing video game franchise?',answers:['Mario','Pokemon','Call of Duty','Minecraft'],correctIndex:1},
    {id:'3ar',tier:3,question:'Which country has the most lakes?',answers:['Finland','Canada','Sweden','Russia'],correctIndex:1},
    {id:'3as',tier:3,question:'What is the most common blood type?',answers:['A','B','AB','O'],correctIndex:3},
    {id:'3at',tier:3,question:'Where is the worlds oldest still-operating library?',answers:['Alexandria','Oxford','Fes','Rome'],correctIndex:2},
    {id:'3au',tier:3,question:'Which planet rotates on its side?',answers:['Neptune','Pluto','Uranus','Saturn'],correctIndex:2},
    {id:'3av',tier:3,question:'What is the largest bird of prey?',answers:['Eagle','Condor','Osprey','Harpy Eagle'],correctIndex:1},
    {id:'3aw',tier:3,question:'Which chemical element has the highest melting point?',answers:['Tungsten','Carbon','Osmium','Rhenium'],correctIndex:0},
    {id:'3ax',tier:3,question:'What is the longest tunnel in the world?',answers:['Channel Tunnel','Gotthard Base Tunnel','Seikan Tunnel','Laerdal Tunnel'],correctIndex:1},
    {id:'3ay',tier:3,question:'Which country has the highest population density?',answers:['Singapore','Bangladesh','Monaco','South Korea'],correctIndex:2},
    {id:'3az',tier:3,question:'Who discovered penicillin?',answers:['Louis Pasteur','Alexander Fleming','Robert Koch','Joseph Lister'],correctIndex:1},
    {id:'3ba',tier:3,question:'What is the largest archipelago in the world?',answers:['Philippines','Indonesia','Japan','Maldives'],correctIndex:1},
    {id:'3bb',tier:3,question:'Which gas gives neon signs their color?',answers:['Argon','Krypton','Neon','Xenon'],correctIndex:2},
    {id:'3bc',tier:3,question:'What is the highest waterfall in the world?',answers:['Niagara','Victoria','Angel','Iguazu'],correctIndex:2},
    {id:'3bd',tier:3,question:'Which country is the largest coconut producer?',answers:['Philippines','Indonesia','India','Sri Lanka'],correctIndex:1},
    {id:'3be',tier:3,question:'What is the only mammal that cannot jump?',answers:['Sloth','Elephant','Hippopotamus','Rhinoceros'],correctIndex:1},
    {id:'3bf',tier:3,question:'Which element has the highest electrical conductivity?',answers:['Copper','Gold','Silver','Aluminum'],correctIndex:2},
    {id:'3bg',tier:3,question:'What is the longest river in Europe?',answers:['Danube','Rhine','Volga','Seine'],correctIndex:2},
    {id:'3bh',tier:3,question:'Which country is the largest producer of cocoa?',answers:['Ghana','Ivory Coast','Nigeria','Ecuador'],correctIndex:1},
    {id:'3bi',tier:3,question:'What is the most common isotope of hydrogen?',answers:['Deuterium','Tritium','Protium','Quadrium'],correctIndex:2},
    {id:'3bj',tier:3,question:'Which brain structure is responsible for balance?',answers:['Cerebrum','Cerebellum','Brain Stem','Hypothalamus'],correctIndex:1},
    {id:'3bk',tier:3,question:'What year was the European Union established?',answers:['1991','1992','1993','1994'],correctIndex:2},
    {id:'3bl',tier:3,question:'Which planet has the strongest magnetic field?',answers:['Earth','Saturn','Jupiter','Neptune'],correctIndex:2},
    {id:'3bm',tier:3,question:'What is the largest desert in Asia?',answers:['Arabian','Gobi','Karakum','Thar'],correctIndex:1},
    {id:'3bn',tier:3,question:'Which country has the most lakes?',answers:['Canada','Finland','Sweden','Russia'],correctIndex:0},
    {id:'3bo',tier:3,question:'What is the only planet that rotates clockwise?',answers:['Mercury','Venus','Mars','Uranus'],correctIndex:1},
    {id:'3bp',tier:3,question:'Which animal has no vocal cords?',answers:['Snake','Giraffe','Fish','Octopus'],correctIndex:1},
    {id:'3bq',tier:3,question:'What is the most expensive spice by weight?',answers:['Vanilla','Saffron','Cardamom','Cinnamon'],correctIndex:1},
    {id:'3br',tier:3,question:'Which composer wrote the Four Seasons?',answers:['Bach','Mozart','Vivaldi','Tchaikovsky'],correctIndex:2},
    {id:'3bs',tier:3,question:'What is the only metal that is not solid at room temperature?',answers:['Gallium','Mercury','Cesium','Francium'],correctIndex:1},
    {id:'3bt',tier:3,question:'Which river is the longest in South America?',answers:['Parana','Orinoco','Amazon','Magdalena'],correctIndex:2},
    {id:'3bu',tier:3,question:'What is the most abundant protein in the human body?',answers:['Hemoglobin','Collagen','Keratin','Myosin'],correctIndex:1},
    {id:'3bv',tier:3,question:'Which country has the most airports?',answers:['China','USA','Brazil','Russia'],correctIndex:1},
    {id:'3bw',tier:3,question:'What is the largest species of deer?',answers:['Moose','Elk','Caribou','White-tailed Deer'],correctIndex:0},
    {id:'3bx',tier:3,question:'Which element is needed for strong bones?',answers:['Iron','Magnesium','Calcium','Potassium'],correctIndex:2},
    {id:'3by',tier:3,question:'What is the longest bone in the human leg?',answers:['Tibia','Fibula','Femur','Patella'],correctIndex:2},
    {id:'3bz',tier:3,question:'Which country is the largest palm oil producer?',answers:['Malaysia','Nigeria','Thailand','Indonesia'],correctIndex:3},
    {id:'3ca',tier:3,question:'What is the most reactive element?',answers:['Sodium','Potassium','Fluorine','Chlorine'],correctIndex:2},
    {id:'3cb',tier:3,question:'Which ancient wonder was located in Babylon?',answers:['Colossus','Hanging Gardens','Lighthouse','Mausoleum'],correctIndex:1},
    {id:'3cc',tier:3,question:'What is the longest-running TV show?',answers:['Simpsons','Doctor Who','Sesame Street','Coronation Street'],correctIndex:0},
    {id:'3cd',tier:3,question:'Which element is a liquid at room temperature?',answers:['Bromine','Iodine','Chlorine','Fluorine'],correctIndex:0},
    {id:'3ce',tier:3,question:'What is the highest mountain in Africa?',answers:['Mount Kenya','Mount Kilimanjaro','Mount Stanley','Rwenzori'],correctIndex:1},
    {id:'3cf',tier:3,question:'Which country invented chess?',answers:['China','Persia','India','Greece'],correctIndex:2},
    {id:'3cg',tier:3,question:'What is the largest species of turtle?',answers:['Green Sea Turtle','Leatherback','Hawksbill','Loggerhead'],correctIndex:1},
    {id:'3ch',tier:3,question:'Which organ can regenerate itself?',answers:['Heart','Kidney','Liver','Pancreas'],correctIndex:2},
    {id:'3ci',tier:3,question:'What is the most consumed meat in the world?',answers:['Beef','Chicken','Pork','Lamb'],correctIndex:2},
    {id:'3cj',tier:3,question:'Which country has the most natural lakes?',answers:['Canada','USA','Finland','Russia'],correctIndex:0},
    {id:'3ck',tier:3,question:'What is the smallest particle of an element?',answers:['Electron','Proton','Atom','Neutron'],correctIndex:2},
    {id:'3cl',tier:3,question:'Which country is the largest producer of bananas?',answers:['Ecuador','Philippines','India','China'],correctIndex:2},
    {id:'3cm',tier:3,question:'What is the deepest part of the ocean?',answers:['Tonga Trench','Mariana Trench','Java Trench','Puerto Rico Trench'],correctIndex:1},
    {id:'3cn',tier:3,question:'Which planet has the fastest winds?',answers:['Jupiter','Saturn','Neptune','Uranus'],correctIndex:2},
    {id:'3co',tier:3,question:'What is the most widely used plastic in the world?',answers:['PVC','Polyethylene','Polypropylene','Polystyrene'],correctIndex:1},
    {id:'3cp',tier:3,question:'Which city is called the Eternal City?',answers:['Athens','Rome','Jerusalem','Cairo'],correctIndex:1},
    {id:'3cq',tier:3,question:'What is the largest internal organ in the human body?',answers:['Heart','Lungs','Liver','Kidneys'],correctIndex:2},
    {id:'3cr',tier:3,question:'Which country has the world largest railway station?',answers:['Japan','China','USA','India'],correctIndex:0},
    {id:'3cs',tier:3,question:'What is the fastest bird in level flight?',answers:['Eagle','Swift','Falcon','Hummingbird'],correctIndex:1},
    {id:'3ct',tier:3,question:'Which element is known as the King of Chemicals?',answers:['Hydrochloric Acid','Nitric Acid','Sulfuric Acid','Phosphoric Acid'],correctIndex:2},
    {id:'3cu',tier:3,question:'What is the largest country by area entirely in Europe?',answers:['Germany','France','Ukraine','Spain'],correctIndex:1},
    {id:'3cv',tier:3,question:'Which animal has three hearts?',answers:['Octopus','Squid','Cuttlefish','Earthworm'],correctIndex:0},
    {id:'3cw',tier:3,question:'What is the most popular programming language?',answers:['Python','Java','JavaScript','C++'],correctIndex:2},
    {id:'3cx',tier:3,question:'Which country had the highest inflation rate in history?',answers:['Germany','Zimbabwe','Hungary','Venezuela'],correctIndex:2},
    {id:'3cy',tier:3,question:'What is the largest species of eagle?',answers:['Bald Eagle','Golden Eagle','Harpy Eagle','Philippine Eagle'],correctIndex:3},
    {id:'3cz',tier:3,question:'Which famous scientist was born on January 8, 1942?',answers:['Einstein','Hawking','Newton','Galileo'],correctIndex:1},
    {id:'3da',tier:3,question:'What is the longest-lived known animal?',answers:['Elephant','Greenland Shark','Galapagos Tortoise','Bowhead Whale'],correctIndex:3},
    {id:'3db',tier:3,question:'Which element is used in the core of nuclear reactors?',answers:['Plutonium','Uranium','Thorium','Radium'],correctIndex:1},
    {id:'3dc',tier:3,question:'What is the largest population city in Africa?',answers:['Cairo','Lagos','Kinshasa','Nairobi'],correctIndex:1},
    {id:'3dd',tier:3,question:'Which natural disaster is measured with the Richter scale?',answers:['Tsunami','Volcano','Earthquake','Tornado'],correctIndex:2},
    {id:'3de',tier:3,question:'What is the most common element in the human body?',answers:['Carbon','Hydrogen','Oxygen','Nitrogen'],correctIndex:2},
  ],
  4: [
    {id:'4a',tier:4,question:'Who wrote The Great Gatsby?',answers:['Ernest Hemingway','F. Scott Fitzgerald','John Steinbeck','William Faulkner'],correctIndex:1},
    {id:'4b',tier:4,question:'What is the second law of thermodynamics?',answers:['Energy is conserved','Entropy always increases','Heat flows hot to cold','Matter cannot be created'],correctIndex:1},
    {id:'4c',tier:4,question:'Which city is home to the worlds oldest stock exchange?',answers:['London','New York','Amsterdam','Tokyo'],correctIndex:2},
    {id:'4d',tier:4,question:'What is the rarest blood type in the world?',answers:['AB-negative','B-negative','Rh-null','A-negative'],correctIndex:2},
    {id:'4e',tier:4,question:'Which element has the atomic number 79?',answers:['Platinum','Mercury','Gold','Silver'],correctIndex:2},
    {id:'4f',tier:4,question:'Who discovered radioactivity?',answers:['Marie Curie','Henri Becquerel','Ernest Rutherford','Wilhelm Roentgen'],correctIndex:1},
    {id:'4g',tier:4,question:'What is the oldest written language?',answers:['Egyptian','Sumerian','Chinese','Sanskrit'],correctIndex:1},
    {id:'4h',tier:4,question:'Which quantum number describes spin?',answers:['n','l','m','s'],correctIndex:3},
    {id:'4i',tier:4,question:'What is the largest basilica in the world?',answers:['Notre Dame','St. Peters','St. Pauls','Westminster Abbey'],correctIndex:1},
    {id:'4j',tier:4,question:'Which element has the highest boiling point?',answers:['Tungsten','Rhenium','Osmium','Carbon'],correctIndex:0},
    {id:'4k',tier:4,question:'What is the longest mountain range underwater?',answers:['Mid-Atlantic Ridge','East Pacific Rise','Hawaiian-Emperor','Indian Ridge'],correctIndex:0},
    {id:'4l',tier:4,question:'Who was the last Pharaoh of Egypt?',answers:['Nefertiti','Cleopatra','Hatshepsut','Ramses'],correctIndex:1},
    {id:'4m',tier:4,question:'What is the most abundant element in the universe by mass?',answers:['Helium','Oxygen','Hydrogen','Carbon'],correctIndex:2},
    {id:'4n',tier:4,question:'Which country has the most vending machines per capita?',answers:['USA','Japan','Germany','South Korea'],correctIndex:1},
    {id:'4o',tier:4,question:'What is the hardest natural material?',answers:['Wurtzite boron nitride','Lonsdaleite','Diamond','Graphene'],correctIndex:2},
    {id:'4p',tier:4,question:'Which bird can fly backward?',answers:['Sparrow','Swallow','Hummingbird','Finch'],correctIndex:2},
    {id:'4q',tier:4,question:'What is the oldest civilization in the Americas?',answers:['Olmec','Maya','Inca','Aztec'],correctIndex:0},
    {id:'4r',tier:4,question:'Which element has the smallest atomic radius?',answers:['Lithium','Helium','Hydrogen','Fluorine'],correctIndex:1},
    {id:'4s',tier:4,question:'What is the longest suspension bridge in the world?',answers:['Golden Gate','Akashi Kaikyo','Mackinac','Tsing Ma'],correctIndex:1},
    {id:'4t',tier:4,question:'Which country invented paper money?',answers:['China','India','Persia','Rome'],correctIndex:0},
    {id:'4u',tier:4,question:'What is the largest animal cell?',answers:['Nerve cell','Muscle cell','Ostrich egg','Fat cell'],correctIndex:2},
    {id:'4v',tier:4,question:'Who painted the ceiling of the Sistine Chapel?',answers:['Raphael','Da Vinci','Michelangelo','Botticelli'],correctIndex:2},
    {id:'4w',tier:4,question:'Which gas gives Uranus its blue-green color?',answers:['Ammonia','Methane','Helium','Hydrogen'],correctIndex:1},
    {id:'4x',tier:4,question:'What is the smallest unit of a chemical compound?',answers:['Atom','Electron','Molecule','Proton'],correctIndex:2},
    {id:'4y',tier:4,question:'Which country has the worlds longest road tunnel?',answers:['Switzerland','Norway','Japan','China'],correctIndex:1},
    {id:'4z',tier:4,question:'Who was the first woman to win a Nobel Prize?',answers:['Rosalind Franklin','Marie Curie','Lise Meitner','Dorothy Hodgkin'],correctIndex:1},
    {id:'4aa',tier:4,question:'What is the largest peninsula in the world?',answers:['Iberian','Scandinavian','Arabian','Indian'],correctIndex:2},
    {id:'4ab',tier:4,question:'Which element is used in the production of glass?',answers:['Carbon','Silicon','Sodium','Calcium'],correctIndex:1},
    {id:'4ac',tier:4,question:'What is the most venomous fish?',answers:['Stonefish','Pufferfish','Lionfish','Box Jellyfish'],correctIndex:0},
    {id:'4ad',tier:4,question:'Which planet has the most moons?',answers:['Jupiter','Saturn','Uranus','Neptune'],correctIndex:1},
    {id:'4ae',tier:4,question:'Who invented the printing press?',answers:['Caxton','Gutenberg','Franklin','Da Vinci'],correctIndex:1},
    {id:'4af',tier:4,question:'What is the largest contract in professional sports history?',answers:['Messi','Ronaldo','Mahomes','Ohtani'],correctIndex:3},
    {id:'4ag',tier:4,question:'Which chemical element has the longest half-life?',answers:['Uranium-238','Thorium-232','Plutonium-244','Bismuth-209'],correctIndex:3},
    {id:'4ah',tier:4,question:'What is the deepest cave in the world?',answers:['Krubera','Veryovkina','Sarma','Snezhnaya'],correctIndex:0},
    {id:'4ai',tier:4,question:'Which country has the highest number of islands?',answers:['Sweden','Finland','Norway','Indonesia'],correctIndex:0},
    {id:'4aj',tier:4,question:'What is the rarest eye color?',answers:['Blue','Green','Gray','Amber'],correctIndex:2},
    {id:'4ak',tier:4,question:'Who was the youngest US President?',answers:['JFK','Teddy Roosevelt','Obama','Clinton'],correctIndex:1},
    {id:'4al',tier:4,question:'Which element is used to make rechargeable batteries?',answers:['Nickel','Cobalt','Lithium','Cadmium'],correctIndex:2},
    {id:'4am',tier:4,question:'What is the largest fish species?',answers:['Great White Shark','Whale Shark','Basking Shark','Manta Ray'],correctIndex:1},
    {id:'4an',tier:4,question:'Which country has the oldest continuously running company?',answers:['Japan','Italy','China','Germany'],correctIndex:0},
    {id:'4ao',tier:4,question:'What is the most common letter in the English language?',answers:['A','E','S','T'],correctIndex:1},
    {id:'4ap',tier:4,question:'Which element is a metalloid?',answers:['Silicon','Aluminum','Tin','Lead'],correctIndex:0},
    {id:'4aq',tier:4,question:'What is the size of a proton?',answers:['1 nanometer','1 femtometer','1 picometer','1 attometer'],correctIndex:1},
    {id:'4ar',tier:4,question:'Which country has the highest average elevation?',answers:['Nepal','Bhutan','Bolivia','Tajikistan'],correctIndex:1},
    {id:'4as',tier:4,question:'Who discovered the laws of motion?',answers:['Einstein','Galileo','Newton','Kepler'],correctIndex:2},
    {id:'4at',tier:4,question:'What is the most powerful muscle in the human body?',answers:['Heart','Masseter','Gluteus','Tongue'],correctIndex:1},
    {id:'4au',tier:4,question:'Which element is named after the Norse god of thunder?',answers:['Neptunium','Thorium','Uranium','Plutonium'],correctIndex:1},
    {id:'4av',tier:4,question:'What is the shortest war in history?',answers:['Anglo-Zanzibar','Franco-Prussian','Six-Day War','Falklands'],correctIndex:0},
    {id:'4aw',tier:4,question:'Which animal has the most bones?',answers:['Snake','Elephant','Shark','Giraffe'],correctIndex:2},
    {id:'4ax',tier:4,question:'What is the largest collection of musical works?',answers:['Library of Congress','British Library','Vatican Library','National Library of China'],correctIndex:0},
    {id:'4ay',tier:4,question:'Which country consumes the most chocolate per capita?',answers:['Belgium','Switzerland','Germany','Austria'],correctIndex:1},
    {id:'4az',tier:4,question:'What is the only element named after a living person?',answers:['Curium','Einsteinium','Oganesson','Seaborgium'],correctIndex:2},
    {id:'4ba',tier:4,question:'Which mountain is the highest peak in North America?',answers:['Mount Logan','Denali','Mount Whitney','Pico de Orizaba'],correctIndex:1},
    {id:'4bb',tier:4,question:'What is the largest Roman structure still standing?',answers:['Colosseum','Pantheon','Aqueduct of Segovia','Temple of Jupiter'],correctIndex:0},
    {id:'4bc',tier:4,question:'Which chemical element is most abundant in the Earth core?',answers:['Iron','Nickel','Oxygen','Silicon'],correctIndex:0},
    {id:'4bd',tier:4,question:'How many U.S. presidents have been assassinated?',answers:['2','3','4','5'],correctIndex:2},
    {id:'4be',tier:4,question:'Which language is the oldest still spoken?',answers:['Greek','Hebrew','Tamil','Egyptian'],correctIndex:2},
    {id:'4bf',tier:4,question:'What is the most radioactive element?',answers:['Polonium','Radium','Uranium','Francium'],correctIndex:0},
    {id:'4bg',tier:4,question:'Which planet has the most circular orbit?',answers:['Earth','Venus','Neptune','Mercury'],correctIndex:1},
    {id:'4bh',tier:4,question:'What is the longest palindrome in English?',answers:['Racecar','Tattarrattat','Aibohphobia','Redivider'],correctIndex:1},
    {id:'4bi',tier:4,question:'Which country has the highest life expectancy?',answers:['Japan','Switzerland','Singapore','Monaco'],correctIndex:3},
    {id:'4bj',tier:4,question:'What is the largest telescope ever built?',answers:['James Webb','Hubble','ELT','Arecibo'],correctIndex:2},
    {id:'4bk',tier:4,question:'Which scientist proposed the theory of evolution?',answers:['Lamarck','Darwin','Mendel','Wallace'],correctIndex:1},
    {id:'4bl',tier:4,question:'What is the most common mineral on Earth?',answers:['Quartz','Feldspar','Olivine','Calcite'],correctIndex:1},
    {id:'4bm',tier:4,question:'Which country has the worlds largest army?',answers:['USA','India','China','Russia'],correctIndex:2},
    {id:'4bn',tier:4,question:'What is the driest continent?',answers:['Australia','Africa','Antarctica','Asia'],correctIndex:2},
    {id:'4bo',tier:4,question:'Which element is used in atomic clocks?',answers:['Cesium','Rubidium','Hydrogen','Strontium'],correctIndex:0},
    {id:'4bp',tier:4,question:'What is the largest delta in the world?',answers:['Nile Delta','Ganges Delta','Mekong Delta','Amazon Delta'],correctIndex:1},
    {id:'4bq',tier:4,question:'Who composed the Moonlight Sonata?',answers:['Mozart','Schubert','Beethoven','Chopin'],correctIndex:2},
    {id:'4br',tier:4,question:'Which country has the most Nobel laureates?',answers:['UK','Germany','USA','France'],correctIndex:2},
    {id:'4bs',tier:4,question:'What is the largest living structure on Earth?',answers:['Amazon Rainforest','Great Barrier Reef','Taiga','Boreal Forest'],correctIndex:1},
    {id:'4bt',tier:4,question:'Which element is essential for thyroid function?',answers:['Iron','Zinc','Iodine','Selenium'],correctIndex:2},
    {id:'4bu',tier:4,question:'What is the fastest-spinning object in the universe?',answers:['Pulsar','Black Hole','Neutron Star','Quasar'],correctIndex:0},
    {id:'4bv',tier:4,question:'Who wrote A Brief History of Time?',answers:['Carl Sagan','Stephen Hawking','Richard Dawkins','Neil deGrasse Tyson'],correctIndex:1},
    {id:'4bw',tier:4,question:'What is the most common infectious disease in humans?',answers:['Tuberculosis','Malaria','Common cold','Influenza'],correctIndex:2},
    {id:'4bx',tier:4,question:'Which country has the most natural gas reserves?',answers:['Qatar','Iran','Russia','USA'],correctIndex:2},
    {id:'4by',tier:4,question:'What is the smallest ape?',answers:['Gibbon','Orangutan','Chimpanzee','Bonobo'],correctIndex:0},
    {id:'4bz',tier:4,question:'Which element has the symbol Sn?',answers:['Silver','Sodium','Tin','Strontium'],correctIndex:2},
    {id:'4ca',tier:4,question:'What is the largest cold desert?',answers:['Gobi','Sahara','Antarctica','Karakum'],correctIndex:2},
    {id:'4cb',tier:4,question:'Which country invented basketball?',answers:['UK','Canada','USA','Australia'],correctIndex:1},
    {id:'4cc',tier:4,question:'What is the strongest muscle relative to its size?',answers:['Heart','Jaw','Tongue','Eye'],correctIndex:1},
    {id:'4cd',tier:4,question:'Which element has the highest density?',answers:['Iridium','Osmium','Platinum','Gold'],correctIndex:1},
    {id:'4ce',tier:4,question:'What is the oldest city in the world?',answers:['Jericho','Athens','Damascus','Jerusalem'],correctIndex:0},
    {id:'4cf',tier:4,question:'Which animal has the most teeth?',answers:['Snail','Shark','Dolphin','Armadillo'],correctIndex:0},
    {id:'4cg',tier:4,question:'What is the highest possible IQ score ever recorded?',answers:['210','228','240','300'],correctIndex:1},
    {id:'4ch',tier:4,question:'Which country is the largest uranium producer?',answers:['Kazakhstan','Canada','Australia','Namibia'],correctIndex:0},
    {id:'4ci',tier:4,question:'What is the most common cancer in men?',answers:['Lung','Colorectal','Prostate','Skin'],correctIndex:2},
    {id:'4cj',tier:4,question:'Which scientist discovered the neutron?',answers:['Rutherford','Chadwick','Bohr','Fermi'],correctIndex:1},
    {id:'4ck',tier:4,question:'What is the largest church in the world?',answers:['St. Peters','St. Pauls','Notre Dame','Cologne Cathedral'],correctIndex:0},
    {id:'4cl',tier:4,question:'Which country has the most tornadoes?',answers:['India','USA','Australia','Bangladesh'],correctIndex:1},
    {id:'4cm',tier:4,question:'What is the most stable element?',answers:['Lead','Gold','Iron','Mercury'],correctIndex:2},
    {id:'4cn',tier:4,question:'Which planet has a density less than water?',answers:['Mars','Venus','Saturn','Jupiter'],correctIndex:2},
    {id:'4co',tier:4,question:'Who invented the light bulb?',answers:['Edison','Tesla','Swan','Westinghouse'],correctIndex:0},
    {id:'4cp',tier:4,question:'What is the longest word in the English language?',answers:['Antidisestablishment','Pneumonoultramicroscopicsilicovolcanoconiosis','Floccinaucinihilipilification','Hippopotomonstrosesquippedaliophobia'],correctIndex:1},
    {id:'4cq',tier:4,question:'Which country is the largest producer of tin?',answers:['China','Indonesia','Peru','Bolivia'],correctIndex:0},
    {id:'4cr',tier:4,question:'What is the most common cause of blindness?',answers:['Glaucoma','Cataracts','Macular degeneration','Diabetic retinopathy'],correctIndex:1},
    {id:'4cs',tier:4,question:'Which element is named after the Greek word for light?',answers:['Phosphorus','Neon','Fluorine','Chlorine'],correctIndex:0},
    {id:'4ct',tier:4,question:'What is the fastest creature on Earth?',answers:['Cheetah','Peregrine Falcon','Sailfish','Spotted Hyena'],correctIndex:1},
    {id:'4cu',tier:4,question:'Which country has the longest highway?',answers:['Russia','Canada','USA','Australia'],correctIndex:2},
    {id:'4cv',tier:4,question:'What is the smallest particle of light?',answers:['Electron','Proton','Photon','Neutrino'],correctIndex:2},
    {id:'4cw',tier:4,question:'Who discovered the circulation of blood?',answers:['Harvey','Galen','Vesalius','Pasteur'],correctIndex:0},
    {id:'4cx',tier:4,question:'Which country is the largest producer of wool?',answers:['Australia','China','New Zealand','UK'],correctIndex:0},
    {id:'4cy',tier:4,question:'What is the most abundant organic compound?',answers:['Glucose','Cellulose','Chitin','Starch'],correctIndex:1},
    {id:'4cz',tier:4,question:'Which planet has the longest day?',answers:['Mercury','Venus','Mars','Jupiter'],correctIndex:0},
    {id:'4da',tier:4,question:'What is the oldest known musical instrument?',answers:['Drum','Flute','Harp','Lyre'],correctIndex:1},
    {id:'4db',tier:4,question:'Which chemical element is used to make fertilizer?',answers:['Nitrogen','Oxygen','Hydrogen','Carbon'],correctIndex:0},
    {id:'4dc',tier:4,question:'What is the most common sleep disorder?',answers:['Sleep apnea','Insomnia','Narcolepsy','Restless leg syndrome'],correctIndex:1},
    {id:'4dd',tier:4,question:'Which country has the most TVs per capita?',answers:['USA','Japan','Germany','China'],correctIndex:0},
    {id:'4de',tier:4,question:'What is the largest rodent?',answers:['Beaver','Porcupine','Capybara','Nutria'],correctIndex:2},
  ],
  5: [
    {id:'5a',tier:5,question:'What is the only element named after a Spanish town?',answers:['Americium','Europium','Plutonium','Californium'],correctIndex:2},
    {id:'5b',tier:5,question:'Who discovered the structure of DNA?',answers:['Watson and Crick','Franklin and Wilkins','Mendel and Darwin','Pauling and Corey'],correctIndex:0},
    {id:'5c',tier:5,question:'What is the rarest naturally occurring element?',answers:['Francium','Astatine','Polonium','Radium'],correctIndex:0},
    {id:'5d',tier:5,question:'Which ocean trench is the deepest?',answers:['Mariana Trench','Tonga Trench','Philippine Trench','Kermadec Trench'],correctIndex:0},
    {id:'5e',tier:5,question:'What is the smallest bird egg?',answers:['Hummingbird','Wren','Finch','Vervain Hummingbird'],correctIndex:3},
    {id:'5f',tier:5,question:'Which country has the oldest parliament?',answers:['UK','Iceland','San Marino','Isle of Man'],correctIndex:1},
    {id:'5g',tier:5,question:'What is the most expensive book ever sold?',answers:['Codex Leicester','First Folio','Gutenberg Bible','Bay Psalm Book'],correctIndex:0},
    {id:'5h',tier:5,question:'Which element has the most stable isotopes?',answers:['Tin','Lead','Mercury','Cadmium'],correctIndex:0},
    {id:'5i',tier:5,question:'What is the driest place on Earth?',answers:['Atacama Desert','McMurdo Dry Valleys','Sahara Desert','Death Valley'],correctIndex:1},
    {id:'5j',tier:5,question:'Who was the first person to win two Nobel Prizes?',answers:['Marie Curie','Linus Pauling','John Bardeen','Frederick Sanger'],correctIndex:0},
    {id:'5k',tier:5,question:'What is the largest known star?',answers:['Betelgeuse','UY Scuti','VY Canis Majoris','NML Cygni'],correctIndex:1},
    {id:'5l',tier:5,question:'Which country has the highest number of time zones?',answers:['France','Russia','USA','UK'],correctIndex:0},
    {id:'5m',tier:5,question:'What is the smallest country by land area?',answers:['Monaco','Vatican City','Nauru','Tuvalu'],correctIndex:1},
    {id:'5n',tier:5,question:'Which element has the highest electronegativity?',answers:['Oxygen','Chlorine','Fluorine','Nitrogen'],correctIndex:2},
    {id:'5o',tier:5,question:'What is the longest recorded flight of a chicken?',answers:['13 seconds','30 seconds','1 minute','5 minutes'],correctIndex:0},
    {id:'5p',tier:5,question:'Which chemical compound gives the smell of rain?',answers:['Geosmin','Petrichor','Ozone','Ionone'],correctIndex:0},
    {id:'5q',tier:5,question:'What is the most complex molecule in nature?',answers:['DNA','Protein','ATP','Titin'],correctIndex:3},
    {id:'5r',tier:5,question:'Which country has the highest proportion of millionaires?',answers:['Switzerland','USA','Singapore','Luxembourg'],correctIndex:0},
    {id:'5s',tier:5,question:'What is the only number with its own name in English?',answers:['Eleven','Twelve','Googol','Million'],correctIndex:2},
    {id:'5t',tier:5,question:'Which element is a superconductor at the highest temperature?',answers:['Yttrium','Lanthanum','Bismuth','Mercury'],correctIndex:0},
    {id:'5u',tier:5,question:'What is the oldest known piece of jewelry?',answers:['Shell beads','Copper ring','Bone necklace','Gold earring'],correctIndex:0},
    {id:'5v',tier:5,question:'Who invented the television?',answers:['Farnsworth','Baird','Zworykin','Sarnoff'],correctIndex:1},
    {id:'5w',tier:5,question:'What is the most abundant protein on Earth?',answers:['Collagen','RuBisCO','Keratin','Hemoglobin'],correctIndex:1},
    {id:'5x',tier:5,question:'Which country has the highest frequency of earthquakes?',answers:['Japan','Indonesia','Chile','Vanuatu'],correctIndex:2},
    {id:'5y',tier:5,question:'What is the fastest nerve impulse speed?',answers:['100 m/s','200 m/s','300 m/s','400 m/s'],correctIndex:0},
    {id:'5z',tier:5,question:'Which element melts in your hand?',answers:['Gallium','Cesium','Rubidium','Francium'],correctIndex:0},
    {id:'5aa',tier:5,question:'What is the largest prime number known?',answers:['2^82,589,933-1','2^74,207,281-1','2^77,232,917-1','2^57,885,161-1'],correctIndex:0},
    {id:'5ab',tier:5,question:'Who wrote the first computer program?',answers:['Ada Lovelace','Charles Babbage','Alan Turing','Grace Hopper'],correctIndex:0},
    {id:'5ac',tier:5,question:'What is the world fastest bird in a dive?',answers:['Golden Eagle','Peregrine Falcon','Gyrfalcon','Spine-tailed Swift'],correctIndex:1},
    {id:'5ad',tier:5,question:'Which country has the highest mountain measured from base to peak?',answers:['Nepal','USA','Ecuador','China'],correctIndex:2},
    {id:'5ae',tier:5,question:'What is the most expensive painting ever sold?',answers:['Salvator Mundi','Interchange','The Card Players','Number 5'],correctIndex:0},
    {id:'5af',tier:5,question:'Which bacterium causes the most deaths annually?',answers:['E. coli','Staphylococcus','Mycobacterium tuberculosis','Streptococcus'],correctIndex:2},
    {id:'5ag',tier:5,question:'What is the longest glacier in the world?',answers:['Lambert Glacier','Vatnajokull','Fedchenko Glacier','Siachen Glacier'],correctIndex:0},
    {id:'5ah',tier:5,question:'Which element has the highest specific heat capacity?',answers:['Water','Lithium','Helium','Ammonia'],correctIndex:2},
    {id:'5ai',tier:5,question:'What is the largest living reptile?',answers:['Komodo Dragon','Saltwater Crocodile','Green Anaconda','Leatherback Turtle'],correctIndex:1},
    {id:'5aj',tier:5,question:'Which country produces the most wine?',answers:['France','Italy','Spain','USA'],correctIndex:1},
    {id:'5ak',tier:5,question:'What is the only letter that appears twice in the word "bookkeeper"?',answers:['O','K','E','B'],correctIndex:2},
    {id:'5al',tier:5,question:'Which chemical element has the highest ionization energy?',answers:['Fluorine','Chlorine','Helium','Neon'],correctIndex:2},
    {id:'5am',tier:5,question:'What is the most durable wood?',answers:['Teak','Ebony','Ironwood','Mahogany'],correctIndex:2},
    {id:'5an',tier:5,question:'Who discovered the first vaccine?',answers:['Pasteur','Jenner','Koch','Salk'],correctIndex:1},
    {id:'5ao',tier:5,question:'Which country has the highest divorce rate?',answers:['USA','Russia','Maldives','Belgium'],correctIndex:2},
    {id:'5ap',tier:5,question:'What is the largest moon in the solar system?',answers:['Titan','Ganymede','Europa','Callisto'],correctIndex:1},
    {id:'5aq',tier:5,question:'Which insect can lift 50 times its own body weight?',answers:['Ant','Beetle','Wasp','Grasshopper'],correctIndex:0},
    {id:'5ar',tier:5,question:'What is the most popular name in the world?',answers:['Muhammad','John','James','Wang'],correctIndex:0},
    {id:'5as',tier:5,question:'Which country has the highest consumption of cheese?',answers:['France','USA','Greece','Denmark'],correctIndex:3},
    {id:'5at',tier:5,question:'What is the oldest known city?',answers:['Damascus','Jericho','Aleppo','Athens'],correctIndex:1},
    {id:'5au',tier:5,question:'Which musical note has the highest frequency?',answers:['A','B','C','G'],correctIndex:1},
    {id:'5av',tier:5,question:'What is the only continent with no active volcanoes?',answers:['Europe','Australia','Antarctica','Africa'],correctIndex:1},
    {id:'5aw',tier:5,question:'Which element is the best conductor of heat?',answers:['Silver','Copper','Gold','Diamond'],correctIndex:3},
    {id:'5ax',tier:5,question:'Who was the first billionaire in history?',answers:['Rockefeller','Carnegie','Vanderbilt','John D. Rockefeller'],correctIndex:3},
    {id:'5ay',tier:5,question:'What is the fastest land vehicle?',answers:['Thrust SSC','Bloodhound LSR','Budweiser Rocket','Blue Flame'],correctIndex:0},
    {id:'5az',tier:5,question:'Which country has the largest gold reserves?',answers:['China','USA','Germany','Russia'],correctIndex:1},
    {id:'5ba',tier:5,question:'What is the rarest gemstone?',answers:['Diamond','Ruby','Painite','Tanzanite'],correctIndex:2},
    {id:'5bb',tier:5,question:'Which scientist proposed the uncertainty principle?',answers:['Bohr','Schrodinger','Heisenberg','Pauli'],correctIndex:2},
    {id:'5bc',tier:5,question:'What is the longest war in history?',answers:['Hundred Years War','Thirty Years War','Reconquista','Roman-Persian Wars'],correctIndex:3},
    {id:'5bd',tier:5,question:'Which element was discovered last?',answers:['Oganesson','Tennessine','Nihonium','Moscovium'],correctIndex:0},
    {id:'5be',tier:5,question:'What is the most common congenital condition?',answers:['Down Syndrome','Cleft palate','Color blindness','Heart defect'],correctIndex:2},
    {id:'5bf',tier:5,question:'Which country has the highest youth literacy rate?',answers:['Finland','Japan','North Korea','Andorra'],correctIndex:2},
    {id:'5bg',tier:5,question:'What is the largest amphibian?',answers:['Chinese Giant Salamander','American Bullfrog','Giant Toad','Mudpuppy'],correctIndex:0},
    {id:'5bh',tier:5,question:'Which element has the highest melting point of any metal?',answers:['Tungsten','Rhenium','Osmium','Platinum'],correctIndex:0},
    {id:'5bi',tier:5,question:'What is the oldest continuously inhabited city in the Americas?',answers:['Cusco','Mexico City','St. Augustine','Santo Domingo'],correctIndex:0},
    {id:'5bj',tier:5,question:'Who invented the binary number system?',answers:['Babbage','Pascal','Leibniz','Boole'],correctIndex:2},
    {id:'5bk',tier:5,question:'What is the most common element in the Earth core?',answers:['Oxygen','Silicon','Iron','Nickel'],correctIndex:2},
    {id:'5bl',tier:5,question:'Which country has the highest obesity rate?',answers:['USA','Mexico','Nauru','Saudi Arabia'],correctIndex:2},
    {id:'5bm',tier:5,question:'What is the smallest unit of time?',answers:['Planck time','Zeptosecond','Attosecond','Femtosecond'],correctIndex:0},
    {id:'5bn',tier:5,question:'Which animal has the most complex brain?',answers:['Dolphin','Elephant','Human','Cuttlefish'],correctIndex:2},
    {id:'5bo',tier:5,question:'What is the most abundant acid in the human stomach?',answers:['Citric acid','Hydrochloric acid','Sulfuric acid','Nitric acid'],correctIndex:1},
    {id:'5bp',tier:5,question:'Which country has the largest territorial waters?',answers:['USA','France','Russia','Australia'],correctIndex:1},
    {id:'5bq',tier:5,question:'What is the most expensive substance by weight?',answers:['Antimatter','Californium','Diamond','Platinum'],correctIndex:0},
    {id:'5br',tier:5,question:'Who was the first person to reach the South Pole?',answers:['Amundsen','Scott','Shackleton','Byrd'],correctIndex:0},
    {id:'5bs',tier:5,question:'Which element has the chemical symbol W?',answers:['Wolfram','Tungsten','White lead','Wismuth'],correctIndex:1},
    {id:'5bt',tier:5,question:'What is the longest-running experiment in history?',answers:['Pitch drop experiment','Beverly clock','Oxford Electric Bell','Methuselah tree'],correctIndex:0},
    {id:'5bu',tier:5,question:'Which bird lays the smallest egg relative to its body size?',answers:['Kiwi','Ostrich','Hummingbird','Cassowary'],correctIndex:0},
    {id:'5bv',tier:5,question:'What is the most commonly broken bone?',answers:['Collarbone','Wrist','Ankle','Nose'],correctIndex:0},
    {id:'5bw',tier:5,question:'Which gas makes up 78% of the Earths atmosphere?',answers:['Oxygen','Carbon Dioxide','Nitrogen','Argon'],correctIndex:2},
    {id:'5bx',tier:5,question:'What is the largest organ in a plants body?',answers:['Root','Stem','Leaf','Flower'],correctIndex:0},
    {id:'5by',tier:5,question:'Which country has the highest per capita chocolate consumption?',answers:['Switzerland','Belgium','Germany','USA'],correctIndex:0},
    {id:'5bz',tier:5,question:'What is the brightest star in the night sky?',answers:['Polaris','Sirius','Vega','Betelgeuse'],correctIndex:1},
    {id:'5ca',tier:5,question:'Which element is used to make nuclear weapons?',answers:['Uranium-235','Plutonium-239','Thorium-232','All of the above'],correctIndex:3},
    {id:'5cb',tier:5,question:'What is the oldest known color?',answers:['Red','Blue','Pink','Yellow'],correctIndex:2},
    {id:'5cc',tier:5,question:'Which country has the most universities in the top 100?',answers:['UK','Germany','USA','Japan'],correctIndex:2},
    {id:'5cd',tier:5,question:'What is the longest period of time a human has spent in space?',answers:['365 days','438 days','500 days','687 days'],correctIndex:1},
    {id:'5ce',tier:5,question:'Which chemical element is liquid between 30°C and 2000°C?',answers:['Mercury','Gallium','Bromine','Cesium'],correctIndex:1},
    {id:'5cf',tier:5,question:'Who was the first person to describe the rings of Saturn?',answers:['Galileo','Huygens','Cassini','Newton'],correctIndex:0},
    {id:'5cg',tier:5,question:'What is the most expensive spice in the world?',answers:['Saffron','Vanilla','Cardamom','Cinnamon'],correctIndex:0},
    {id:'5ch',tier:5,question:'Which country has the highest railway density?',answers:['Germany','Japan','Switzerland','Belgium'],correctIndex:2},
    {id:'5ci',tier:5,question:'What is the smallest wavelength of visible light?',answers:['400 nm','500 nm','600 nm','700 nm'],correctIndex:0},
    {id:'5cj',tier:5,question:'Which animal has the most chromosomes?',answers:['Dog','Human','Fern','Crayfish'],correctIndex:2},
    {id:'5ck',tier:5,question:'What is the most abundant element in the Earth crust by volume?',answers:['Oxygen','Silicon','Sodium','Calcium'],correctIndex:0},
    {id:'5cl',tier:5,question:'Which country invented the hot air balloon?',answers:['France','China','Italy','UK'],correctIndex:0},
    {id:'5cm',tier:5,question:'What is the largest known black hole?',answers:['TON 618','Sagittarius A*','M87','Phoenix A'],correctIndex:3},
    {id:'5cn',tier:5,question:'Which element is named after the planet Neptune?',answers:['Neptunium','Plutonium','Uranium','Mercury'],correctIndex:0},
    {id:'5co',tier:5,question:'What is the most durable natural fiber?',answers:['Cotton','Wool','Silk','Hemp'],correctIndex:2},
    {id:'5cp',tier:5,question:'Who was the longest-reigning monarch in history?',answers:['Queen Elizabeth II','Louis XIV','King Sobhuza II','Emperor Hirohito'],correctIndex:2},
    {id:'5cq',tier:5,question:'What is the most common cause of house fires?',answers:['Electrical','Cooking','Smoking','Candles'],correctIndex:1},
    {id:'5cr',tier:5,question:'Which country has the highest per capita GDP?',answers:['Switzerland','Norway','Luxembourg','Qatar'],correctIndex:3},
    {id:'5cs',tier:5,question:'What is the smallest particle of an element?',answers:['Proton','Neutron','Atom','Quark'],correctIndex:3},
    {id:'5ct',tier:5,question:'Which animal can survive the longest without water?',answers:['Camel','Kangaroo Rat','Giraffe','Camel Spider'],correctIndex:1},
    {id:'5cu',tier:5,question:'What is the oldest known fossil?',answers:['Stromatolite','Trilobite','Dinosaur bone','Ammonite'],correctIndex:0},
    {id:'5cv',tier:5,question:'Which element has the highest atomic number?',answers:['Oganesson','Tennessine','Nihonium','Flerovium'],correctIndex:0},
    {id:'5cw',tier:5,question:'What is the most common name for a dog?',answers:['Max','Buddy','Charlie','Bella'],correctIndex:1},
    {id:'5cx',tier:5,question:'Which country has the highest speed limit?',answers:['Germany','Poland','UAE','Italy'],correctIndex:2},
    {id:'5cy',tier:5,question:'What is the smallest known star?',answers:['Proxima Centauri','EBLM J0555-57Ab','Trappist-1','Barnards Star'],correctIndex:1},
    {id:'5cz',tier:5,question:'Which element is used in smoke detectors?',answers:['Americium','Plutonium','Radium','Polonium'],correctIndex:0},
    {id:'5da',tier:5,question:'What is the most common bacterial infection in humans?',answers:['UTI','Strep throat','Food poisoning','Pneumonia'],correctIndex:0},
    {id:'5db',tier:5,question:'Which country has the highest murder rate?',answers:['Venezuela','Honduras','El Salvador','Jamaica'],correctIndex:0},
    {id:'5dc',tier:5,question:'What is the largest volcanic eruption in recorded history?',answers:['Krakatoa','Mount Tambora','Mount Vesuvius','Mount St. Helens'],correctIndex:1},
    {id:'5dd',tier:5,question:'Which element has the symbol Sb?',answers:['Scandium','Antimony','Samarium','Strontium'],correctIndex:1},
    {id:'5de',tier:5,question:'What is the oldest known map?',answers:['Ptolemy world map','Babylonian Imago Mundi','Hereford Mappa Mundi','Piri Reis map'],correctIndex:1},
  ],
}

const DIFFICULTY_MAP: Record<number, number> = {
  1: 1, 2: 1, 3: 1,
  4: 2, 5: 2, 6: 2,
  7: 3, 8: 3, 9: 3, 10: 3,
  11: 4, 12: 4, 13: 4, 14: 4, 15: 5,
}

export function getQuestionsForGame(count = 15): Question[] {
  const usedIds = new Set<string>()
  const result: Question[] = []

  const levels = count === 1 ? [1] : Array.from({ length: count }, (_, i) => i + 1)

  for (const level of levels) {
    const tier = count === 1 ? 1 : DIFFICULTY_MAP[level]
    const pool = QUESTIONS_BY_TIER[tier].filter(q => !usedIds.has(q.id))
    const shuffled = [...pool].sort(() => Math.random() - 0.5)
    if (shuffled.length === 0) continue
    const chosen = shuffled[0]
    usedIds.add(chosen.id)
    const correctText = chosen.answers[chosen.correctIndex]
    const shuffledAnswers = [...chosen.answers].sort(() => Math.random() - 0.5)
    const newCorrectIndex = shuffledAnswers.indexOf(correctText)
    result.push({
      ...chosen,
      answers: shuffledAnswers,
      correctIndex: newCorrectIndex,
    })
  }

  return result
}
